# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/competitor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/competitor.proto',
  package='protos',
  syntax='proto2',
  serialized_pb=_b('\n\x17protos/competitor.proto\x12\x06protos\"M\n\x14\x43ompetitorIdentifier\x12\x15\n\rcompetitor_id\x18\x01 \x01(\t\x12\x1e\n\x16\x63ompetitor_private_key\x18\x02 \x01(\t\"\x82\x01\n\x12\x43ompetitorMetadata\x12;\n\x15\x63ompetitor_identifier\x18\x01 \x01(\x0b\x32\x1c.protos.CompetitorIdentifier\x12\x0b\n\x03pnl\x18\x02 \x02(\x01\x12\r\n\x05\x66ines\x18\x03 \x02(\x01\x12\x13\n\x0b\x63ommissions\x18\x04 \x02(\x01')
)




_COMPETITORIDENTIFIER = _descriptor.Descriptor(
  name='CompetitorIdentifier',
  full_name='protos.CompetitorIdentifier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='competitor_id', full_name='protos.CompetitorIdentifier.competitor_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='competitor_private_key', full_name='protos.CompetitorIdentifier.competitor_private_key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=112,
)


_COMPETITORMETADATA = _descriptor.Descriptor(
  name='CompetitorMetadata',
  full_name='protos.CompetitorMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='competitor_identifier', full_name='protos.CompetitorMetadata.competitor_identifier', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pnl', full_name='protos.CompetitorMetadata.pnl', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fines', full_name='protos.CompetitorMetadata.fines', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='commissions', full_name='protos.CompetitorMetadata.commissions', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=245,
)

_COMPETITORMETADATA.fields_by_name['competitor_identifier'].message_type = _COMPETITORIDENTIFIER
DESCRIPTOR.message_types_by_name['CompetitorIdentifier'] = _COMPETITORIDENTIFIER
DESCRIPTOR.message_types_by_name['CompetitorMetadata'] = _COMPETITORMETADATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CompetitorIdentifier = _reflection.GeneratedProtocolMessageType('CompetitorIdentifier', (_message.Message,), dict(
  DESCRIPTOR = _COMPETITORIDENTIFIER,
  __module__ = 'protos.competitor_pb2'
  # @@protoc_insertion_point(class_scope:protos.CompetitorIdentifier)
  ))
_sym_db.RegisterMessage(CompetitorIdentifier)

CompetitorMetadata = _reflection.GeneratedProtocolMessageType('CompetitorMetadata', (_message.Message,), dict(
  DESCRIPTOR = _COMPETITORMETADATA,
  __module__ = 'protos.competitor_pb2'
  # @@protoc_insertion_point(class_scope:protos.CompetitorMetadata)
  ))
_sym_db.RegisterMessage(CompetitorMetadata)


# @@protoc_insertion_point(module_scope)
