# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/exchange.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/exchange.proto',
  package='protos',
  syntax='proto2',
  serialized_pb=_b('\n\x15protos/exchange.proto\x12\x06protos\"H\n\x05\x41sset\x12\x12\n\nasset_code\x18\x01 \x01(\t\x12\x15\n\rmin_tick_size\x18\x02 \x01(\x02\x12\x14\n\x0cmax_position\x18\x03 \x01(\x05\"}\n\x0e\x45xchangeConfig\x12\x1d\n\x06\x61ssets\x18\x01 \x03(\x0b\x32\r.protos.Asset\x12\x1c\n\x14total_exposure_limit\x18\x02 \x01(\x05\x12.\n\x1f\x62lock_orders_on_risk_violations\x18\x03 \x01(\x08:\x05\x66\x61lse\"0\n\x11MarketUpdateLevel\x12\r\n\x05price\x18\x01 \x01(\x02\x12\x0c\n\x04size\x18\x02 \x01(\x05\"\xb2\x01\n\x0cMarketUpdate\x12\x1c\n\x05\x61sset\x18\x01 \x01(\x0b\x32\r.protos.Asset\x12\x18\n\x10mid_market_price\x18\x02 \x01(\x02\x12\'\n\x04\x62ids\x18\x03 \x03(\x0b\x32\x19.protos.MarketUpdateLevel\x12\'\n\x04\x61sks\x18\x04 \x03(\x0b\x32\x19.protos.MarketUpdateLevel\x12\x0b\n\x03\x62id\x18\x05 \x01(\x02\x12\x0b\n\x03\x61sk\x18\x06 \x01(\x02')
)




_ASSET = _descriptor.Descriptor(
  name='Asset',
  full_name='protos.Asset',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='asset_code', full_name='protos.Asset.asset_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min_tick_size', full_name='protos.Asset.min_tick_size', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_position', full_name='protos.Asset.max_position', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=105,
)


_EXCHANGECONFIG = _descriptor.Descriptor(
  name='ExchangeConfig',
  full_name='protos.ExchangeConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='assets', full_name='protos.ExchangeConfig.assets', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_exposure_limit', full_name='protos.ExchangeConfig.total_exposure_limit', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='block_orders_on_risk_violations', full_name='protos.ExchangeConfig.block_orders_on_risk_violations', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=232,
)


_MARKETUPDATELEVEL = _descriptor.Descriptor(
  name='MarketUpdateLevel',
  full_name='protos.MarketUpdateLevel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='price', full_name='protos.MarketUpdateLevel.price', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='protos.MarketUpdateLevel.size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=282,
)


_MARKETUPDATE = _descriptor.Descriptor(
  name='MarketUpdate',
  full_name='protos.MarketUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='asset', full_name='protos.MarketUpdate.asset', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mid_market_price', full_name='protos.MarketUpdate.mid_market_price', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bids', full_name='protos.MarketUpdate.bids', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='asks', full_name='protos.MarketUpdate.asks', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bid', full_name='protos.MarketUpdate.bid', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ask', full_name='protos.MarketUpdate.ask', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=285,
  serialized_end=463,
)

_EXCHANGECONFIG.fields_by_name['assets'].message_type = _ASSET
_MARKETUPDATE.fields_by_name['asset'].message_type = _ASSET
_MARKETUPDATE.fields_by_name['bids'].message_type = _MARKETUPDATELEVEL
_MARKETUPDATE.fields_by_name['asks'].message_type = _MARKETUPDATELEVEL
DESCRIPTOR.message_types_by_name['Asset'] = _ASSET
DESCRIPTOR.message_types_by_name['ExchangeConfig'] = _EXCHANGECONFIG
DESCRIPTOR.message_types_by_name['MarketUpdateLevel'] = _MARKETUPDATELEVEL
DESCRIPTOR.message_types_by_name['MarketUpdate'] = _MARKETUPDATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Asset = _reflection.GeneratedProtocolMessageType('Asset', (_message.Message,), dict(
  DESCRIPTOR = _ASSET,
  __module__ = 'protos.exchange_pb2'
  # @@protoc_insertion_point(class_scope:protos.Asset)
  ))
_sym_db.RegisterMessage(Asset)

ExchangeConfig = _reflection.GeneratedProtocolMessageType('ExchangeConfig', (_message.Message,), dict(
  DESCRIPTOR = _EXCHANGECONFIG,
  __module__ = 'protos.exchange_pb2'
  # @@protoc_insertion_point(class_scope:protos.ExchangeConfig)
  ))
_sym_db.RegisterMessage(ExchangeConfig)

MarketUpdateLevel = _reflection.GeneratedProtocolMessageType('MarketUpdateLevel', (_message.Message,), dict(
  DESCRIPTOR = _MARKETUPDATELEVEL,
  __module__ = 'protos.exchange_pb2'
  # @@protoc_insertion_point(class_scope:protos.MarketUpdateLevel)
  ))
_sym_db.RegisterMessage(MarketUpdateLevel)

MarketUpdate = _reflection.GeneratedProtocolMessageType('MarketUpdate', (_message.Message,), dict(
  DESCRIPTOR = _MARKETUPDATE,
  __module__ = 'protos.exchange_pb2'
  # @@protoc_insertion_point(class_scope:protos.MarketUpdate)
  ))
_sym_db.RegisterMessage(MarketUpdate)


# @@protoc_insertion_point(module_scope)
