# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/order_book.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import competitor_pb2 as protos_dot_competitor__pb2

from protos.competitor_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/order_book.proto',
  package='protos',
  syntax='proto2',
  serialized_pb=_b('\n\x17protos/order_book.proto\x12\x06protos\x1a\x17protos/competitor.proto\"\xff\x01\n\x05Order\x12\x12\n\nasset_code\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12+\n\norder_type\x18\x03 \x01(\x0e\x32\x17.protos.Order.OrderType\x12\r\n\x05price\x18\x04 \x01(\x02\x12;\n\x15\x63ompetitor_identifier\x18\x05 \x01(\x0b\x32\x1c.protos.CompetitorIdentifier\x12\x1a\n\x12remaining_quantity\x18\x06 \x01(\x05\x12\x10\n\x08order_id\x18\x07 \x01(\t\")\n\tOrderType\x12\r\n\tORDER_MKT\x10\x01\x12\r\n\tORDER_LMT\x10\x02\"\x9b\x01\n\x04\x46ill\x12\x1c\n\x05order\x18\x01 \x01(\x0b\x32\r.protos.Order\x12,\n\x06trader\x18\x02 \x01(\x0b\x32\x1c.protos.CompetitorIdentifier\x12\x17\n\x0f\x66illed_quantity\x18\x03 \x01(\x05\x12\x1a\n\x12remaining_quantity\x18\x04 \x01(\x05\x12\x12\n\nfill_price\x18\x05 \x01(\x02P\x00')
  ,
  dependencies=[protos_dot_competitor__pb2.DESCRIPTOR,],
  public_dependencies=[protos_dot_competitor__pb2.DESCRIPTOR,])



_ORDER_ORDERTYPE = _descriptor.EnumDescriptor(
  name='OrderType',
  full_name='protos.Order.OrderType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ORDER_MKT', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ORDER_LMT', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=275,
  serialized_end=316,
)
_sym_db.RegisterEnumDescriptor(_ORDER_ORDERTYPE)


_ORDER = _descriptor.Descriptor(
  name='Order',
  full_name='protos.Order',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='asset_code', full_name='protos.Order.asset_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='protos.Order.quantity', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='order_type', full_name='protos.Order.order_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='protos.Order.price', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='competitor_identifier', full_name='protos.Order.competitor_identifier', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='remaining_quantity', full_name='protos.Order.remaining_quantity', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='order_id', full_name='protos.Order.order_id', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ORDER_ORDERTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=316,
)


_FILL = _descriptor.Descriptor(
  name='Fill',
  full_name='protos.Fill',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='order', full_name='protos.Fill.order', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trader', full_name='protos.Fill.trader', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filled_quantity', full_name='protos.Fill.filled_quantity', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='remaining_quantity', full_name='protos.Fill.remaining_quantity', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fill_price', full_name='protos.Fill.fill_price', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=319,
  serialized_end=474,
)

_ORDER.fields_by_name['order_type'].enum_type = _ORDER_ORDERTYPE
_ORDER.fields_by_name['competitor_identifier'].message_type = protos_dot_competitor__pb2._COMPETITORIDENTIFIER
_ORDER_ORDERTYPE.containing_type = _ORDER
_FILL.fields_by_name['order'].message_type = _ORDER
_FILL.fields_by_name['trader'].message_type = protos_dot_competitor__pb2._COMPETITORIDENTIFIER
DESCRIPTOR.message_types_by_name['Order'] = _ORDER
DESCRIPTOR.message_types_by_name['Fill'] = _FILL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Order = _reflection.GeneratedProtocolMessageType('Order', (_message.Message,), dict(
  DESCRIPTOR = _ORDER,
  __module__ = 'protos.order_book_pb2'
  # @@protoc_insertion_point(class_scope:protos.Order)
  ))
_sym_db.RegisterMessage(Order)

Fill = _reflection.GeneratedProtocolMessageType('Fill', (_message.Message,), dict(
  DESCRIPTOR = _FILL,
  __module__ = 'protos.order_book_pb2'
  # @@protoc_insertion_point(class_scope:protos.Fill)
  ))
_sym_db.RegisterMessage(Fill)


# @@protoc_insertion_point(module_scope)
