# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from protos import service_pb2 as protos_dot_service__pb2


class ExchangeServiceStub(object):
  """
  service definitions

  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RegisterCompetitor = channel.unary_unary(
        '/protos.ExchangeService/RegisterCompetitor',
        request_serializer=protos_dot_service__pb2.RegisterCompetitorRequest.SerializeToString,
        response_deserializer=protos_dot_service__pb2.RegisterCompetitorResponse.FromString,
        )
    self.GetCompetitorMetadata = channel.unary_unary(
        '/protos.ExchangeService/GetCompetitorMetadata',
        request_serializer=protos_dot_service__pb2.GetCompetitorMetadataRequest.SerializeToString,
        response_deserializer=protos_dot_service__pb2.GetCompetitorMetadataResponse.FromString,
        )
    self.PlaceOrder = channel.unary_unary(
        '/protos.ExchangeService/PlaceOrder',
        request_serializer=protos_dot_service__pb2.PlaceOrderRequest.SerializeToString,
        response_deserializer=protos_dot_service__pb2.PlaceOrderResponse.FromString,
        )
    self.ModifyOrder = channel.unary_unary(
        '/protos.ExchangeService/ModifyOrder',
        request_serializer=protos_dot_service__pb2.ModifyOrderRequest.SerializeToString,
        response_deserializer=protos_dot_service__pb2.ModifyOrderResponse.FromString,
        )
    self.CancelOrder = channel.unary_unary(
        '/protos.ExchangeService/CancelOrder',
        request_serializer=protos_dot_service__pb2.CancelOrderRequest.SerializeToString,
        response_deserializer=protos_dot_service__pb2.CancelOrderResponse.FromString,
        )
    self.GetExchangeUpdate = channel.unary_stream(
        '/protos.ExchangeService/GetExchangeUpdate',
        request_serializer=protos_dot_service__pb2.GetExchangeUpdateRequest.SerializeToString,
        response_deserializer=protos_dot_service__pb2.GetExchangeUpdateResponse.FromString,
        )


class ExchangeServiceServicer(object):
  """
  service definitions

  """

  def RegisterCompetitor(self, request, context):
    """rpc for registering a competitor
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCompetitorMetadata(self, request, context):
    """rpc for getting competitor metadata
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PlaceOrder(self, request, context):
    """rpc for placing an order
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ModifyOrder(self, request, context):
    """rpc for modifying an order
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CancelOrder(self, request, context):
    """rpc for cancelling an order
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetExchangeUpdate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ExchangeServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RegisterCompetitor': grpc.unary_unary_rpc_method_handler(
          servicer.RegisterCompetitor,
          request_deserializer=protos_dot_service__pb2.RegisterCompetitorRequest.FromString,
          response_serializer=protos_dot_service__pb2.RegisterCompetitorResponse.SerializeToString,
      ),
      'GetCompetitorMetadata': grpc.unary_unary_rpc_method_handler(
          servicer.GetCompetitorMetadata,
          request_deserializer=protos_dot_service__pb2.GetCompetitorMetadataRequest.FromString,
          response_serializer=protos_dot_service__pb2.GetCompetitorMetadataResponse.SerializeToString,
      ),
      'PlaceOrder': grpc.unary_unary_rpc_method_handler(
          servicer.PlaceOrder,
          request_deserializer=protos_dot_service__pb2.PlaceOrderRequest.FromString,
          response_serializer=protos_dot_service__pb2.PlaceOrderResponse.SerializeToString,
      ),
      'ModifyOrder': grpc.unary_unary_rpc_method_handler(
          servicer.ModifyOrder,
          request_deserializer=protos_dot_service__pb2.ModifyOrderRequest.FromString,
          response_serializer=protos_dot_service__pb2.ModifyOrderResponse.SerializeToString,
      ),
      'CancelOrder': grpc.unary_unary_rpc_method_handler(
          servicer.CancelOrder,
          request_deserializer=protos_dot_service__pb2.CancelOrderRequest.FromString,
          response_serializer=protos_dot_service__pb2.CancelOrderResponse.SerializeToString,
      ),
      'GetExchangeUpdate': grpc.unary_stream_rpc_method_handler(
          servicer.GetExchangeUpdate,
          request_deserializer=protos_dot_service__pb2.GetExchangeUpdateRequest.FromString,
          response_serializer=protos_dot_service__pb2.GetExchangeUpdateResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'protos.ExchangeService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
